### PR TITLE
update README curand.jl example

### PR DESCRIPTION
**Pull request by waltsims**
Just something minor.

### CODE REVIEW

**Comment by vchuravy** [comment]
Thank you for this.

It might be valuable to have both this example and the previous one in the readme. As far as I know there is a performance difference between using global memory and allocating memory with `new`.

**Review by vchuravy — APPROVED** [review]

**Comment by waltsims** [comment]
I'm still getting used to CUDAnative.jl and what is possible so correct me if i'm wrong, but can one declare an array of type currandState_t, I get an error because the type currandState_t is only part of the [device api](http://docs.nvidia.com/cuda/curand/device-api-overview.html#device-api-overview) and not part of the [host api](http://docs.nvidia.com/cuda/curand/host-api-overview.html#host-api-overview) and therefore not accessible in the main?


when I run:

```
#!/usr/local/bin/julia 

using CUDAdrv, CUDAnative
using CUDAnativelib
using .CURANDkernel # notice the dot prefix

function fillRandom(out, states)
  i = (blockIdx().x-1) * blockDim().x + threadIdx().x
  if i < min(length(out), length(states))
    # Initialise state
    state = pointer(states, i)
    curand_init(0, i, 0, state) # one should use a decent seed here ;)

    @inbounds out[i] = curand_uniform(eltype(out), state) # @inbounds is optional
  end
  return nothing
end

# code_warntype(STDOUT, fillRandom, (CuDeviceArray{Float32,1}, CuDeviceArray{curandState_t,1}))
# code_warntype(STDOUT, fillRandom, (CuDeviceArray{Float64,1}, CuDeviceArray{curandState_t,1}))

# code_llvm(STDOUT, fillRandom, (CuDeviceArray{Float32,1}, CuDeviceArray{curandState_t,1}))
# code_llvm(STDOUT, fillRandom, (CuDeviceArray{Float64,1}, CuDeviceArray{curandState_t,1}))

dev = CuDevice(0)
ctx = CuContext(dev)
N = 100
state = CuArray{curandState_t}(N)
out = CuArray{Float32}(N)
@cuda (N,1) fillRandom(out, state)
```

I get the error:

```
ERROR: LoadError: ArgumentError: CuArray with non-bit element type not supported
Stacktrace:
 [1] Type at /home/wsimson/.julia/v0.6/CUDAdrv/src/array.jl:16 [inlined]
 [2] CUDAdrv.CuArray{Cxx.CppValue{Cxx.CxxQualType{Cxx.CppBaseType{:curandStateXORWOW},(false, false, false)},48},N} where N(::Int64) at /home/wsimson/.julia/v0.6/CUDAdrv/src/array.jl:36
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:300
 [6] _start() at ./client.jl:366
while loading /home/wsimson/WalkingOnSpheres.jl/fillrandom.jl, in expression starting on line 28
```

if i try to compile a comparable code in C++:

```
#include <unistd.h>
#include <stdio.h>

#include <curand.h>
#include <curand_kernel.h>

#define MAX 100

__global__ void random(unsigned int seed, curandState* state, int* result) {
  curand_init(seed,
              0,
              0,
              state);

  *result = curand(&state) % MAX;
}

int main( ) {
  int* gpu_x;
  cudaMalloc((void**) &gpu_x, sizeof(int));

  curandState_t * d_state; 
  cudaMalloc((void**)&d_state,sizeof(curand_state));

  random<<<1, 1>>>(time(NULL),d_state, gpu_x);

  int x;
  cudaMemcpy(&x, gpu_x, sizeof(int), cudaMemcpyDeviceToHost);

  printf("Random number = %d.\n", x);

  cudaFree(gpu_x);

  return 0;
}

```

I get a comparable error:

```
wsimson@m03map28:~/WalkingOnSpheres.jl$ nvcc rand.cu -o rand
rand.cu(23): error: identifier "curand_state" is undefined

1 error detected in the compilation of "/tmp/tmpxft_00004fce_00000000-9_rand.cpp1.ii".
```

One would have to use the host API to generate numbers on the host no?  Does the  original code run on your machine?

**Comment by waltsims** [comment]
when I run:

```
#!/usr/local/bin/julia 

using CUDAdrv, CUDAnative
using CUDAnativelib
using .CURANDkernel # notice the dot prefix

function fillRandom(out, states)
  i = (blockIdx().x-1) * blockDim().x + threadIdx().x
  if i < min(length(out), length(states))
    # Initialise state
    state = pointer(states, i)
    curand_init(0, i, 0, state) # one should use a decent seed here ;)

    @inbounds out[i] = curand_uniform(eltype(out), state) # @inbounds is optional
  end
  return nothing
end

# code_warntype(STDOUT, fillRandom, (CuDeviceArray{Float32,1}, CuDeviceArray{curandState_t,1}))
# code_warntype(STDOUT, fillRandom, (CuDeviceArray{Float64,1}, CuDeviceArray{curandState_t,1}))

# code_llvm(STDOUT, fillRandom, (CuDeviceArray{Float32,1}, CuDeviceArray{curandState_t,1}))
# code_llvm(STDOUT, fillRandom, (CuDeviceArray{Float64,1}, CuDeviceArray{curandState_t,1}))

dev = CuDevice(0)
ctx = CuContext(dev)
N = 100
state = CuArray{curandState_t}(N)
out = CuArray{Float32}(N)
@cuda (N,1) fillRandom(out, state)
```

I get the error:

```
ERROR: LoadError: ArgumentError: CuArray with non-bit element type not supported
Stacktrace:
 [1] Type at /home/wsimson/.julia/v0.6/CUDAdrv/src/array.jl:16 [inlined]
 [2] CUDAdrv.CuArray{Cxx.CppValue{Cxx.CxxQualType{Cxx.CppBaseType{:curandStateXORWOW},(false, false, false)},48},N} where N(::Int64) at /home/wsimson/.julia/v0.6/CUDAdrv/src/array.jl:36
 [3] include_from_node1(::String) at ./loading.jl:539
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:300
 [6] _start() at ./client.jl:366
while loading /home/wsimson/WalkingOnSpheres.jl/fillrandom.jl, in expression starting on line 28
```

does that run for you? I know you can do something similar in C++.

**Comment by vchuravy** [comment]
Hm, I remember this working originally. @maleadt I remember us having a conversation about requiring `isbits` fur `CuArray` at some point.

**Pull request merged**
